Repository OWASP/Top10, pull requests merged in 2021-09, with the labels that each got.

#578 Update A00_2021_How_to_use_the_OWASP_Top_10_as_a_standard.md
  2021/docs/A00_2021_How_to_use_the_OWASP_Top_10_as_a_standard.md
Labels: Links will be resolved by OSIB

#589 Update A10_2021-Server-Side_Request_Forgery_(SSRF).md
  2021/docs/A10_2021-Server-Side_Request_Forgery_(SSRF).md
Labels: A10

#607 A04_2021-Insecure_Design: Extend Description
  2021/docs/A04_2021-Insecure_Design.md
Labels: A4

#624 2021 fr
  2021/docs/A01_2021-Broken_Access_Control.fr.md
  2021/docs/index.fr.md
Labels: translations

#623 Add Arabic Language
  2021/docs/0x00-notice.ar.md
  2021/docs/A00-about-owasp.ar.md
  2021/docs/A00_2021-How_to_start_an_AppSec_program_with_the_OWASP_Top_10.ar.md
  2021/docs/A00_2021_How_to_use_the_OWASP_Top_10_as_a_standard.ar.md
  2021/docs/A00_2021_Introduction.ar.md
  2021/docs/A01_2021-Broken_Access_Control.ar.md
  2021/docs/A02_2021-Cryptographic_Failures.ar.md
  2021/docs/A03_2021-Injection.ar.md
  2021/docs/A04_2021-Insecure_Design.ar.md
  2021/docs/A05_2021-Security_Misconfiguration.ar.md
  2021/docs/A06_2021-Vulnerable_and_Outdated_Components.ar.md
  2021/docs/A07_2021-Identification_and_Authentication_Failures.ar.md
  2021/docs/A08_2021-Software_and_Data_Integrity_Failures.ar.md
  2021/docs/A09_2021-Security_Logging_and_Monitoring_Failures.ar.md
  2021/docs/A10_2021-Server-Side_Request_Forgery_(SSRF).ar.md
  2021/docs/A11_2021-Next_Steps.ar.md
  2021/docs/ar/assets/LICENSE-FRONT-WASP.txt
  2021/docs/ar/assets/OWASP_Logo_Transp.png
  2021/docs/ar/assets/OWASP_logo.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Broken_Access_Control.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Crypto_Failures.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Identification_and_Authentication_Failures.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Injection.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Insecure_Design.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Insecure_Design_100.png
  2021/docs/ar/assets/TOP_10_Icons_Final_SSRF.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Security_Logging_and_Monitoring_Failures.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Security_Misconfiguration.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Software_and_Data_Integrity_Failures.png
  2021/docs/ar/assets/TOP_10_Icons_Final_Vulnerable_Outdated_Components.png
  2021/docs/ar/assets/TOP_10_logo_Final_Logo_Colour.png
  2021/docs/ar/assets/front-cc.png
  2021/docs/ar/assets/front-wasp.png
  2021/docs/ar/assets/image1.png
  2021/docs/ar/assets/image2.png
  2021/docs/ar/assets/license.png
  2021/docs/ar/assets/mapping.png
  2021/docs/ar/assets/readme.md
  2021/docs/ar/assets/securecodewarrior.png
  2021/docs/index.ar.md
  2021/mkdocs.yml
Labels: translations

#634 Fix bullet paragraph
  2021/docs/A07_2021-Identification_and_Authentication_Failures.md
Labels: bug

#635 Fix typo
  2021/docs/A10_2021-Server-Side_Request_Forgery_(SSRF).md
Labels: bug
